# Generated by Django 6.0 on 2025-12-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Пусто', max_length=100, verbose_name='Введи автора книги')),
                ('title', models.CharField(default='Пусто', max_length=200, verbose_name='Введи название книги')),
            ],
        ),
    ]
