# Generated by Django 5.2.9 on 2025-12-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_aboutyou_day_birth_remove_aboutyou_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutyou',
            name='photo',
        ),
    ]
