# Generated by Django 5.2.9 on 2025-12-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_aboutyou_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutyou',
            name='author',
            field=models.CharField(default='Пусто', max_length=100, verbose_name='Введи автора книги'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='day_made',
            field=models.IntegerField(default=2000, verbose_name='Когда написано'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='jenre',
            field=models.TextField(default='роман', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='aboutyou',
            name='pages',
            field=models.IntegerField(default=200, verbose_name='Сколько страниц'),
        ),
    ]
