# Generated by Django 5.2.9 on 2025-12-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_aboutyou_author_alter_aboutyou_day_made_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutyou',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aboutyou',
            name='day_made',
        ),
        migrations.RemoveField(
            model_name='aboutyou',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='aboutyou',
            name='jenre',
        ),
        migrations.RemoveField(
            model_name='aboutyou',
            name='pages',
        ),
        migrations.AddField(
            model_name='aboutyou',
            name='title',
            field=models.CharField(default='Пусто', max_length=200, verbose_name='Введи название книги'),
        ),
    ]
